"""initial schema: 17 tables for the RAG platform

Hand-written (not autogenerated) so the tenant indexes are explicit and reviewable.
Every tenant-scoped table gets a plain index on tenant_id plus a composite index on
(tenant_id, <natural key>) — the composite is what turns a tenant-scoped lookup into
an index seek.

Revision ID: 0001
Revises:
Create Date: 2026-08-01

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# JSONB on Postgres, JSON elsewhere (sqlite in tests).
JSON = postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite")
TS = sa.DateTime(timezone=True)
ID = sa.String(64)
SHORT = sa.String(255)
URI = sa.String(2048)


def _now() -> sa.sql.functions.Function[sa.DateTime]:
    """Server default for creation timestamps.

    Returns:
        ``func.now()``, which SQLAlchemy compiles per dialect (``now()`` on
        PostgreSQL, ``CURRENT_TIMESTAMP`` on sqlite). This matches the ORM models,
        which use ``func.now()`` too, and keeps the migration applicable to the
        sqlite database the schema tests use.
    """
    return sa.func.now()


def upgrade() -> None:
    """Create the whole schema."""
    # ------------------------------------------------------------ 1. tenants
    op.create_table(
        "tenants",
        sa.Column("tenant_id", ID, nullable=False),
        sa.Column("name", SHORT, nullable=False),
        sa.Column("entra_tenant_id", ID, nullable=True),
        sa.Column("display_domain", SHORT, nullable=True),
        sa.Column(
            "default_classification",
            sa.String(32),
            nullable=False,
            server_default="internal",
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("settings", JSON, nullable=False, server_default=sa.text("'{}'")),
        sa.Column("created_at", TS, nullable=False, server_default=_now()),
        sa.Column("updated_at", TS, nullable=False, server_default=_now()),
        sa.PrimaryKeyConstraint("tenant_id", name="pk_tenants"),
        sa.UniqueConstraint("entra_tenant_id", name="uq_tenants_entra_tenant_id"),
    )
    op.create_index("ix_tenants_is_active", "tenants", ["is_active"])

    # -------------------------------------------------------------- 2. users
    op.create_table(
        "users",
        sa.Column("user_id", ID, nullable=False),
        sa.Column("tenant_id", ID, nullable=False),
        sa.Column("email", SHORT, nullable=True),
        sa.Column("display_name", SHORT, nullable=True),
        sa.Column("roles", JSON, nullable=False, server_default=sa.text("'[]'")),
        sa.Column("groups", JSON, nullable=False, server_default=sa.text("'[]'")),
        sa.Column(
            "max_classification",
            sa.String(32),
            nullable=False,
            server_default="internal",
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("last_seen_at", TS, nullable=True),
        sa.Column("created_at", TS, nullable=False, server_default=_now()),
        sa.Column("updated_at", TS, nullable=False, server_default=_now()),
        sa.PrimaryKeyConstraint("user_id", name="pk_users"),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
            name="fk_users_tenant_id_tenants",
            ondelete="CASCADE",
        ),
    )
    op.create_index("ix_users_tenant_id", "users", ["tenant_id"])
    op.create_index("ix_users_tenant_id_email", "users", ["tenant_id", "email"])
    op.create_index(
        "ix_users_tenant_id_last_seen_at", "users", ["tenant_id", "last_seen_at"]
    )

    # ----------------------------------------------------- 3. source_configs
    op.create_table(
        "source_configs",
        sa.Column("source_id", ID, nullable=False),
        sa.Column("tenant_id", ID, nullable=False),
        sa.Column("source_type", sa.String(32), nullable=False),
        sa.Column("name", SHORT, nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("options", JSON, nullable=False, server_default=sa.text("'{}'")),
        sa.Column(
            "default_classification",
            sa.String(32),
            nullable=False,
            server_default="internal",
        ),
        sa.Column(
            "default_allowed_roles",
            JSON,
            nullable=False,
            server_default=sa.text("'[]'"),
        ),
        sa.Column(
            "default_allowed_groups",
            JSON,
            nullable=False,
            server_default=sa.text("'[]'"),
        ),
        sa.Column(
            "default_allowed_users",
            JSON,
            nullable=False,
            server_default=sa.text("'[]'"),
        ),
        sa.Column(
            "default_denied_users", JSON, nullable=False, server_default=sa.text("'[]'")
        ),
        sa.Column(
            "inherit_source_permissions",
            sa.Boolean(),
            nullable=False,
            server_default=sa.true(),
        ),
        sa.Column("doc_type", sa.String(64), nullable=False, server_default="document"),
        sa.Column("tags", JSON, nullable=False, server_default=sa.text("'[]'")),
        sa.Column("language", sa.String(16), nullable=False, server_default="en"),
        sa.Column("cron_override", sa.String(128), nullable=True),
        sa.Column("timezone_override", sa.String(64), nullable=True),
        sa.Column("cursor", sa.Text(), nullable=True),
        sa.Column("cursor_updated_at", TS, nullable=True),
        sa.Column("last_run_id", ID, nullable=True),
        sa.Column("last_run_at", TS, nullable=True),
        sa.Column("last_status", sa.String(32), nullable=True),
        sa.Column("created_at", TS, nullable=False, server_default=_now()),
        sa.Column("updated_at", TS, nullable=False, server_default=_now()),
        sa.PrimaryKeyConstraint("source_id", name="pk_source_configs"),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
            name="fk_source_configs_tenant_id_tenants",
            ondelete="CASCADE",
        ),
        sa.UniqueConstraint(
            "tenant_id", "name", name="uq_source_configs_tenant_id_name"
        ),
    )
    op.create_index("ix_source_configs_tenant_id", "source_configs", ["tenant_id"])
    op.create_index(
        "ix_source_configs_tenant_id_source_type",
        "source_configs",
        ["tenant_id", "source_type"],
    )
    op.create_index(
        "ix_source_configs_tenant_id_enabled",
        "source_configs",
        ["tenant_id", "enabled"],
    )

    # ---------------------------------------------------------- 4. documents
    op.create_table(
        "documents",
        sa.Column("document_id", ID, nullable=False),
        sa.Column("tenant_id", ID, nullable=False),
        sa.Column("source_id", ID, nullable=True),
        sa.Column("source_type", sa.String(32), nullable=False),
        sa.Column("source_uri", URI, nullable=False),
        sa.Column("title", SHORT, nullable=False, server_default=""),
        sa.Column("doc_type", sa.String(64), nullable=False, server_default="document"),
        sa.Column("language", sa.String(16), nullable=False, server_default="en"),
        sa.Column("author", SHORT, nullable=True),
        sa.Column("content_sha256", sa.String(64), nullable=False, server_default=""),
        sa.Column("simhash", sa.String(16), nullable=False, server_default=""),
        sa.Column("etag", SHORT, nullable=True),
        sa.Column("acl_fingerprint", sa.String(64), nullable=False, server_default=""),
        sa.Column("version", sa.Integer(), nullable=False, server_default="1"),
        sa.Column(
            "classification", sa.String(32), nullable=False, server_default="internal"
        ),
        sa.Column(
            "classification_rank", sa.Integer(), nullable=False, server_default="1"
        ),
        sa.Column(
            "allowed_roles", JSON, nullable=False, server_default=sa.text("'[]'")
        ),
        sa.Column(
            "allowed_groups", JSON, nullable=False, server_default=sa.text("'[]'")
        ),
        sa.Column(
            "allowed_users", JSON, nullable=False, server_default=sa.text("'[]'")
        ),
        sa.Column("denied_users", JSON, nullable=False, server_default=sa.text("'[]'")),
        sa.Column("tags", JSON, nullable=False, server_default=sa.text("'[]'")),
        sa.Column("keywords", JSON, nullable=False, server_default=sa.text("'[]'")),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("chunk_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("token_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False, server_default="0"),
        sa.Column("source_modified_at", TS, nullable=True),
        sa.Column("effective_from", TS, nullable=True),
        sa.Column("effective_to", TS, nullable=True),
        sa.Column("pii_types", JSON, nullable=False, server_default=sa.text("'[]'")),
        sa.Column(
            "pii_redacted", sa.Boolean(), nullable=False, server_default=sa.false()
        ),
        sa.Column(
            "is_deleted", sa.Boolean(), nullable=False, server_default=sa.false()
        ),
        sa.Column("deleted_at", TS, nullable=True),
        sa.Column("ingest_run_id", ID, nullable=True),
        sa.Column("blob_url", URI, nullable=True),
        sa.Column("extra", JSON, nullable=False, server_default=sa.text("'{}'")),
        sa.Column("created_at", TS, nullable=False, server_default=_now()),
        sa.Column("updated_at", TS, nullable=False, server_default=_now()),
        sa.PrimaryKeyConstraint("document_id", name="pk_documents"),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
            name="fk_documents_tenant_id_tenants",
            ondelete="CASCADE",
        ),
        sa.UniqueConstraint(
            "tenant_id", "source_uri", name="uq_documents_tenant_id_source_uri"
        ),
    )
    op.create_index("ix_documents_tenant_id", "documents", ["tenant_id"])
    op.create_index(
        "ix_documents_tenant_id_source_id", "documents", ["tenant_id", "source_id"]
    )
    op.create_index(
        "ix_documents_tenant_id_content_sha256",
        "documents",
        ["tenant_id", "content_sha256"],
    )
    op.create_index(
        "ix_documents_tenant_id_is_deleted", "documents", ["tenant_id", "is_deleted"]
    )
    op.create_index(
        "ix_documents_tenant_id_doc_type", "documents", ["tenant_id", "doc_type"]
    )
    op.create_index(
        "ix_documents_tenant_id_source_modified_at",
        "documents",
        ["tenant_id", "source_modified_at"],
    )
    op.create_index(
        "ix_documents_tenant_id_ingest_run_id",
        "documents",
        ["tenant_id", "ingest_run_id"],
    )

    # -------------------------------------------------------- 5. ingest_runs
    op.create_table(
        "ingest_runs",
        sa.Column("run_id", ID, nullable=False),
        sa.Column("tenant_id", ID, nullable=False),
        sa.Column("source_id", ID, nullable=True),
        sa.Column("trigger", sa.String(32), nullable=False, server_default="timer"),
        sa.Column("status", sa.String(32), nullable=False, server_default="running"),
        sa.Column("started_at", TS, nullable=False, server_default=_now()),
        sa.Column("finished_at", TS, nullable=True),
        sa.Column("documents_seen", sa.Integer(), nullable=False, server_default="0"),
        sa.Column(
            "documents_created", sa.Integer(), nullable=False, server_default="0"
        ),
        sa.Column(
            "documents_updated", sa.Integer(), nullable=False, server_default="0"
        ),
        sa.Column(
            "documents_deleted", sa.Integer(), nullable=False, server_default="0"
        ),
        sa.Column(
            "documents_skipped", sa.Integer(), nullable=False, server_default="0"
        ),
        sa.Column("documents_failed", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("chunks_upserted", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("chunks_deleted", sa.Integer(), nullable=False, server_default="0"),
        sa.Column(
            "tokens_embedded", sa.BigInteger(), nullable=False, server_default="0"
        ),
        sa.Column(
            "duplicates_dropped", sa.Integer(), nullable=False, server_default="0"
        ),
        sa.Column("pii_documents", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("forced", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column(
            "within_working_hours",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
        sa.Column("skip_reason", sa.String(64), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("metrics", JSON, nullable=False, server_default=sa.text("'{}'")),
        sa.PrimaryKeyConstraint("run_id", name="pk_ingest_runs"),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
            name="fk_ingest_runs_tenant_id_tenants",
            ondelete="CASCADE",
        ),
    )
    op.create_index("ix_ingest_runs_tenant_id", "ingest_runs", ["tenant_id"])
    op.create_index(
        "ix_ingest_runs_tenant_id_started_at",
        "ingest_runs",
        ["tenant_id", "started_at"],
    )
    op.create_index(
        "ix_ingest_runs_tenant_id_source_id", "ingest_runs", ["tenant_id", "source_id"]
    )
    op.create_index(
        "ix_ingest_runs_tenant_id_status", "ingest_runs", ["tenant_id", "status"]
    )

    # ------------------------------------------------------- 6. ingest_items
    op.create_table(
        "ingest_items",
        sa.Column("item_id", ID, nullable=False),
        sa.Column("run_id", ID, nullable=False),
        sa.Column("tenant_id", ID, nullable=False),
        sa.Column("document_id", ID, nullable=True),
        sa.Column("source_uri", URI, nullable=False),
        sa.Column("action", sa.String(32), nullable=False),
        sa.Column("status", sa.String(32), nullable=False),
        sa.Column("reason", SHORT, nullable=True),
        sa.Column("chunk_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("token_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column(
            "duplicates_dropped", sa.Integer(), nullable=False, server_default="0"
        ),
        sa.Column("duration_ms", sa.Float(), nullable=False, server_default="0"),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", TS, nullable=False, server_default=_now()),
        sa.PrimaryKeyConstraint("item_id", name="pk_ingest_items"),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["ingest_runs.run_id"],
            name="fk_ingest_items_run_id_ingest_runs",
            ondelete="CASCADE",
        ),
    )
    op.create_index("ix_ingest_items_tenant_id", "ingest_items", ["tenant_id"])
    op.create_index(
        "ix_ingest_items_tenant_id_run_id", "ingest_items", ["tenant_id", "run_id"]
    )
    op.create_index(
        "ix_ingest_items_tenant_id_document_id",
        "ingest_items",
        ["tenant_id", "document_id"],
    )
    op.create_index(
        "ix_ingest_items_run_id_status", "ingest_items", ["run_id", "status"]
    )

    # ------------------------------------------------------ 7. chat_sessions
    op.create_table(
        "chat_sessions",
        sa.Column("session_id", ID, nullable=False),
        sa.Column("tenant_id", ID, nullable=False),
        sa.Column("user_id", ID, nullable=False),
        sa.Column("title", SHORT, nullable=False, server_default=""),
        sa.Column(
            "is_archived", sa.Boolean(), nullable=False, server_default=sa.false()
        ),
        sa.Column("rolling_summary", sa.Text(), nullable=False, server_default=""),
        sa.Column("summary_tokens", sa.Integer(), nullable=False, server_default="0"),
        sa.Column(
            "compaction_events", sa.Integer(), nullable=False, server_default="0"
        ),
        sa.Column("message_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column(
            "total_input_tokens", sa.BigInteger(), nullable=False, server_default="0"
        ),
        sa.Column(
            "total_output_tokens", sa.BigInteger(), nullable=False, server_default="0"
        ),
        sa.Column(
            "total_cache_read_tokens",
            sa.BigInteger(),
            nullable=False,
            server_default="0",
        ),
        sa.Column("total_cost_usd", sa.Float(), nullable=False, server_default="0"),
        sa.Column("last_message_at", TS, nullable=True),
        sa.Column("created_at", TS, nullable=False, server_default=_now()),
        sa.Column("updated_at", TS, nullable=False, server_default=_now()),
        sa.PrimaryKeyConstraint("session_id", name="pk_chat_sessions"),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
            name="fk_chat_sessions_tenant_id_tenants",
            ondelete="CASCADE",
        ),
    )
    op.create_index("ix_chat_sessions_tenant_id", "chat_sessions", ["tenant_id"])
    op.create_index(
        "ix_chat_sessions_tenant_id_user_id", "chat_sessions", ["tenant_id", "user_id"]
    )
    op.create_index(
        "ix_chat_sessions_tenant_id_user_id_last_message_at",
        "chat_sessions",
        ["tenant_id", "user_id", "last_message_at"],
    )

    # ------------------------------------------------------ 8. chat_messages
    op.create_table(
        "chat_messages",
        sa.Column("message_id", ID, nullable=False),
        sa.Column("tenant_id", ID, nullable=False),
        sa.Column("session_id", ID, nullable=False),
        sa.Column("user_id", ID, nullable=False),
        sa.Column("role", sa.String(16), nullable=False),
        sa.Column("content", sa.Text(), nullable=False, server_default=""),
        sa.Column("token_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("citations", JSON, nullable=False, server_default=sa.text("'[]'")),
        sa.Column("tool_calls", JSON, nullable=False, server_default=sa.text("'[]'")),
        sa.Column(
            "guardrail_events", JSON, nullable=False, server_default=sa.text("'[]'")
        ),
        sa.Column(
            "context_stats", JSON, nullable=False, server_default=sa.text("'{}'")
        ),
        sa.Column("usage", JSON, nullable=False, server_default=sa.text("'{}'")),
        sa.Column(
            "suppressed", sa.Boolean(), nullable=False, server_default=sa.false()
        ),
        sa.Column("pinned", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column(
            "pii_redacted", sa.Boolean(), nullable=False, server_default=sa.false()
        ),
        sa.Column("pii_types", JSON, nullable=False, server_default=sa.text("'[]'")),
        sa.Column("model", sa.String(64), nullable=True),
        sa.Column("latency_ms", sa.Float(), nullable=False, server_default="0"),
        sa.Column("cost_usd", sa.Float(), nullable=False, server_default="0"),
        sa.Column("trace_id", ID, nullable=True),
        sa.Column("stop_reason", sa.String(32), nullable=True),
        sa.Column("refused", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("created_at", TS, nullable=False, server_default=_now()),
        sa.PrimaryKeyConstraint("message_id", name="pk_chat_messages"),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["chat_sessions.session_id"],
            name="fk_chat_messages_session_id_chat_sessions",
            ondelete="CASCADE",
        ),
    )
    op.create_index("ix_chat_messages_tenant_id", "chat_messages", ["tenant_id"])
    op.create_index(
        "ix_chat_messages_tenant_id_session_id_created_at",
        "chat_messages",
        ["tenant_id", "session_id", "created_at"],
    )
    op.create_index(
        "ix_chat_messages_tenant_id_user_id", "chat_messages", ["tenant_id", "user_id"]
    )
    op.create_index(
        "ix_chat_messages_tenant_id_trace_id",
        "chat_messages",
        ["tenant_id", "trace_id"],
    )

    # --------------------------------------------------- 9. tool_invocations
    op.create_table(
        "tool_invocations",
        sa.Column("tool_call_id", ID, nullable=False),
        sa.Column("tenant_id", ID, nullable=False),
        sa.Column("session_id", ID, nullable=True),
        sa.Column("message_id", ID, nullable=True),
        sa.Column("user_id", ID, nullable=True),
        sa.Column("tool_name", SHORT, nullable=False),
        sa.Column("kind", sa.String(32), nullable=False),
        sa.Column("arguments", JSON, nullable=False, server_default=sa.text("'{}'")),
        sa.Column("result_summary", sa.Text(), nullable=True),
        sa.Column("is_error", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("truncated", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("latency_ms", sa.Float(), nullable=False, server_default="0"),
        sa.Column("trace_id", ID, nullable=True),
        sa.Column("created_at", TS, nullable=False, server_default=_now()),
        sa.PrimaryKeyConstraint("tool_call_id", name="pk_tool_invocations"),
    )
    op.create_index("ix_tool_invocations_tenant_id", "tool_invocations", ["tenant_id"])
    op.create_index(
        "ix_tool_invocations_tenant_id_session_id",
        "tool_invocations",
        ["tenant_id", "session_id"],
    )
    op.create_index(
        "ix_tool_invocations_tenant_id_message_id",
        "tool_invocations",
        ["tenant_id", "message_id"],
    )
    op.create_index(
        "ix_tool_invocations_tenant_id_tool_name_created_at",
        "tool_invocations",
        ["tenant_id", "tool_name", "created_at"],
    )

    # ----------------------------------------------------- 10. user_profiles
    op.create_table(
        "user_profiles",
        sa.Column("tenant_id", ID, nullable=False),
        sa.Column("user_id", ID, nullable=False),
        sa.Column("summary", sa.Text(), nullable=False, server_default=""),
        sa.Column("preferred_style", SHORT, nullable=True),
        sa.Column("preferred_language", sa.String(16), nullable=True),
        sa.Column("top_topics", JSON, nullable=False, server_default=sa.text("'[]'")),
        sa.Column(
            "memory_consent", sa.Boolean(), nullable=False, server_default=sa.true()
        ),
        sa.Column(
            "turns_since_refresh", sa.Integer(), nullable=False, server_default="0"
        ),
        sa.Column("created_at", TS, nullable=False, server_default=_now()),
        sa.Column("updated_at", TS, nullable=False, server_default=_now()),
        sa.PrimaryKeyConstraint("tenant_id", "user_id", name="pk_user_profiles"),
    )
    op.create_index("ix_user_profiles_tenant_id", "user_profiles", ["tenant_id"])

    # ----------------------------------------------------- 11. user_memories
    op.create_table(
        "user_memories",
        sa.Column("memory_id", ID, nullable=False),
        sa.Column("tenant_id", ID, nullable=False),
        sa.Column("user_id", ID, nullable=False),
        sa.Column("kind", sa.String(32), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("salience", sa.Float(), nullable=False, server_default="0.5"),
        sa.Column("source_session_id", ID, nullable=True),
        sa.Column("supersedes", ID, nullable=True),
        sa.Column("superseded_by", ID, nullable=True),
        sa.Column("hit_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column(
            "pii_redacted", sa.Boolean(), nullable=False, server_default=sa.false()
        ),
        sa.Column("embedded", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column(
            "is_deleted", sa.Boolean(), nullable=False, server_default=sa.false()
        ),
        sa.Column("created_at", TS, nullable=False, server_default=_now()),
        sa.Column("last_used_at", TS, nullable=True),
        sa.Column("expires_at", TS, nullable=True),
        sa.PrimaryKeyConstraint("memory_id", name="pk_user_memories"),
    )
    op.create_index("ix_user_memories_tenant_id", "user_memories", ["tenant_id"])
    op.create_index(
        "ix_user_memories_tenant_id_user_id_kind",
        "user_memories",
        ["tenant_id", "user_id", "kind"],
    )
    op.create_index(
        "ix_user_memories_tenant_id_user_id_salience",
        "user_memories",
        ["tenant_id", "user_id", "salience"],
    )
    op.create_index(
        "ix_user_memories_tenant_id_expires_at",
        "user_memories",
        ["tenant_id", "expires_at"],
    )

    # ----------------------------------------------- 12. semantic_cache_meta
    op.create_table(
        "semantic_cache_meta",
        sa.Column("cache_id", ID, nullable=False),
        sa.Column("tenant_id", ID, nullable=False),
        sa.Column("user_id", ID, nullable=True),
        sa.Column("normalized_query", sa.Text(), nullable=False),
        sa.Column(
            "transformed_queries", JSON, nullable=False, server_default=sa.text("'[]'")
        ),
        sa.Column("chunk_ids", JSON, nullable=False, server_default=sa.text("'[]'")),
        sa.Column("filter_fingerprint", sa.String(64), nullable=False),
        sa.Column("hit_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("ttl_seconds", sa.Integer(), nullable=False, server_default="86400"),
        sa.Column("created_at", TS, nullable=False, server_default=_now()),
        sa.Column("last_used_at", TS, nullable=False, server_default=_now()),
        sa.Column("expires_at", TS, nullable=True),
        sa.PrimaryKeyConstraint("cache_id", name="pk_semantic_cache_meta"),
    )
    op.create_index(
        "ix_semantic_cache_meta_tenant_id", "semantic_cache_meta", ["tenant_id"]
    )
    op.create_index(
        "ix_semantic_cache_meta_tenant_id_filter_fingerprint",
        "semantic_cache_meta",
        ["tenant_id", "filter_fingerprint"],
    )
    op.create_index(
        "ix_semantic_cache_meta_tenant_id_user_id",
        "semantic_cache_meta",
        ["tenant_id", "user_id"],
    )
    op.create_index(
        "ix_semantic_cache_meta_tenant_id_expires_at",
        "semantic_cache_meta",
        ["tenant_id", "expires_at"],
    )

    # -------------------------------------------------- 13. lineage_records
    op.create_table(
        "lineage_records",
        sa.Column("lineage_id", ID, nullable=False),
        sa.Column("kind", sa.String(32), nullable=False),
        sa.Column("tenant_id", ID, nullable=False),
        sa.Column("user_id", ID, nullable=True),
        sa.Column("session_id", ID, nullable=True),
        sa.Column("trace_id", ID, nullable=True),
        sa.Column("subject_id", ID, nullable=False),
        sa.Column("parents", JSON, nullable=False, server_default=sa.text("'[]'")),
        sa.Column("operation", SHORT, nullable=False),
        sa.Column("actor", SHORT, nullable=False),
        sa.Column("inputs", JSON, nullable=False, server_default=sa.text("'{}'")),
        sa.Column("outputs", JSON, nullable=False, server_default=sa.text("'{}'")),
        sa.Column("metrics", JSON, nullable=False, server_default=sa.text("'{}'")),
        sa.Column("created_at", TS, nullable=False, server_default=_now()),
        sa.PrimaryKeyConstraint("lineage_id", name="pk_lineage_records"),
    )
    op.create_index("ix_lineage_records_tenant_id", "lineage_records", ["tenant_id"])
    op.create_index(
        "ix_lineage_records_tenant_id_subject_id",
        "lineage_records",
        ["tenant_id", "subject_id"],
    )
    op.create_index(
        "ix_lineage_records_tenant_id_kind_created_at",
        "lineage_records",
        ["tenant_id", "kind", "created_at"],
    )
    op.create_index(
        "ix_lineage_records_tenant_id_trace_id",
        "lineage_records",
        ["tenant_id", "trace_id"],
    )

    # --------------------------------------------------------- 14. eval_runs
    op.create_table(
        "eval_runs",
        sa.Column("run_id", ID, nullable=False),
        sa.Column("tenant_id", ID, nullable=False),
        sa.Column("started_at", TS, nullable=False, server_default=_now()),
        sa.Column("finished_at", TS, nullable=True),
        sa.Column("git_sha", sa.String(64), nullable=True),
        sa.Column(
            "config_fingerprint", sa.String(64), nullable=False, server_default=""
        ),
        sa.Column("golden_set_path", URI, nullable=True),
        sa.Column("aggregate", JSON, nullable=False, server_default=sa.text("'{}'")),
        sa.Column(
            "gate_passed", sa.Boolean(), nullable=False, server_default=sa.false()
        ),
        sa.Column("item_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("passed_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("failed_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("total_cost_usd", sa.Float(), nullable=False, server_default="0"),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("run_id", name="pk_eval_runs"),
    )
    op.create_index("ix_eval_runs_tenant_id", "eval_runs", ["tenant_id"])
    op.create_index(
        "ix_eval_runs_tenant_id_started_at", "eval_runs", ["tenant_id", "started_at"]
    )
    op.create_index(
        "ix_eval_runs_tenant_id_gate_passed", "eval_runs", ["tenant_id", "gate_passed"]
    )

    # ------------------------------------------------------ 15. eval_results
    op.create_table(
        "eval_results",
        sa.Column("result_id", ID, nullable=False),
        sa.Column("run_id", ID, nullable=False),
        sa.Column("tenant_id", ID, nullable=False),
        sa.Column("item_id", ID, nullable=False),
        sa.Column("category", sa.String(32), nullable=True),
        sa.Column("question", sa.Text(), nullable=True),
        sa.Column("answer", sa.Text(), nullable=False, server_default=""),
        sa.Column(
            "retrieved_chunk_ids", JSON, nullable=False, server_default=sa.text("'[]'")
        ),
        sa.Column("scores", JSON, nullable=False, server_default=sa.text("'{}'")),
        sa.Column("passed", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("failures", JSON, nullable=False, server_default=sa.text("'[]'")),
        sa.Column("latency_ms", sa.Float(), nullable=False, server_default="0"),
        sa.Column("cost_usd", sa.Float(), nullable=False, server_default="0"),
        sa.Column("trace_id", ID, nullable=True),
        sa.Column("created_at", TS, nullable=False, server_default=_now()),
        sa.PrimaryKeyConstraint("result_id", name="pk_eval_results"),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["eval_runs.run_id"],
            name="fk_eval_results_run_id_eval_runs",
            ondelete="CASCADE",
        ),
        sa.UniqueConstraint("run_id", "item_id", name="uq_eval_results_run_id_item_id"),
    )
    op.create_index("ix_eval_results_tenant_id", "eval_results", ["tenant_id"])
    op.create_index(
        "ix_eval_results_tenant_id_run_id", "eval_results", ["tenant_id", "run_id"]
    )
    op.create_index(
        "ix_eval_results_tenant_id_item_id", "eval_results", ["tenant_id", "item_id"]
    )
    op.create_index(
        "ix_eval_results_run_id_passed", "eval_results", ["run_id", "passed"]
    )

    # ---------------------------------------------------------- 16. feedback
    op.create_table(
        "feedback",
        sa.Column("feedback_id", ID, nullable=False),
        sa.Column("tenant_id", ID, nullable=False),
        sa.Column("user_id", ID, nullable=False),
        sa.Column("session_id", ID, nullable=True),
        sa.Column("message_id", ID, nullable=True),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("tags", JSON, nullable=False, server_default=sa.text("'[]'")),
        sa.Column("trace_id", ID, nullable=True),
        sa.Column("langfuse_score_id", ID, nullable=True),
        sa.Column(
            "pii_redacted", sa.Boolean(), nullable=False, server_default=sa.false()
        ),
        sa.Column("created_at", TS, nullable=False, server_default=_now()),
        sa.PrimaryKeyConstraint("feedback_id", name="pk_feedback"),
    )
    op.create_index("ix_feedback_tenant_id", "feedback", ["tenant_id"])
    op.create_index(
        "ix_feedback_tenant_id_message_id", "feedback", ["tenant_id", "message_id"]
    )
    op.create_index(
        "ix_feedback_tenant_id_session_id", "feedback", ["tenant_id", "session_id"]
    )
    op.create_index(
        "ix_feedback_tenant_id_created_at", "feedback", ["tenant_id", "created_at"]
    )

    # --------------------------------------------------------- 17. audit_log
    op.create_table(
        "audit_log",
        sa.Column("audit_id", ID, nullable=False),
        sa.Column("tenant_id", ID, nullable=False),
        sa.Column("user_id", ID, nullable=True),
        sa.Column("action", SHORT, nullable=False),
        sa.Column("resource_type", sa.String(64), nullable=True),
        sa.Column("resource_id", ID, nullable=True),
        sa.Column("outcome", sa.String(32), nullable=False, server_default="allow"),
        sa.Column("detail", JSON, nullable=False, server_default=sa.text("'{}'")),
        sa.Column("ip_address", sa.String(64), nullable=True),
        sa.Column("user_agent", SHORT, nullable=True),
        sa.Column("trace_id", ID, nullable=True),
        sa.Column("created_at", TS, nullable=False, server_default=_now()),
        sa.PrimaryKeyConstraint("audit_id", name="pk_audit_log"),
    )
    op.create_index("ix_audit_log_tenant_id", "audit_log", ["tenant_id"])
    op.create_index(
        "ix_audit_log_tenant_id_created_at", "audit_log", ["tenant_id", "created_at"]
    )
    op.create_index(
        "ix_audit_log_tenant_id_action", "audit_log", ["tenant_id", "action"]
    )
    op.create_index(
        "ix_audit_log_tenant_id_user_id", "audit_log", ["tenant_id", "user_id"]
    )
    op.create_index(
        "ix_audit_log_tenant_id_outcome", "audit_log", ["tenant_id", "outcome"]
    )


def downgrade() -> None:
    """Drop the whole schema, children before parents."""
    for table in (
        "audit_log",
        "feedback",
        "eval_results",
        "eval_runs",
        "lineage_records",
        "semantic_cache_meta",
        "user_memories",
        "user_profiles",
        "tool_invocations",
        "chat_messages",
        "chat_sessions",
        "ingest_items",
        "ingest_runs",
        "documents",
        "source_configs",
        "users",
        "tenants",
    ):
        op.drop_table(table)
