"""SQLAlchemy 2.0 async engine, session factory and declarative base.

The engine is cached per database URL so every service in a process shares one
connection pool. ``get_session`` is the FastAPI dependency; ``session_scope`` is the
equivalent for non-HTTP callers (Azure Functions activities, the eval harness,
scripts).

Both hand out a session that has **not** begun a transaction. Callers that write use
``async with session.begin():`` (or the repositories in
:mod:`ragcore.db.repositories`, which commit explicitly), so a read path never holds
an idle transaction open against Azure Database for PostgreSQL.
"""

from __future__ import annotations

from collections.abc import AsyncIterator
from contextlib import asynccontextmanager
from datetime import datetime
from typing import Any

from sqlalchemy import JSON, DateTime, MetaData, Text, event, text
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.ext.asyncio import (
    AsyncEngine,
    AsyncSession,
    async_sessionmaker,
    create_async_engine,
)
from sqlalchemy.orm import DeclarativeBase
from sqlalchemy.pool import NullPool

from ragcore.settings import Settings, get_settings

__all__ = [
    "JSON_TYPE",
    "Base",
    "dispose_engine",
    "get_engine",
    "get_session",
    "get_sessionmaker",
    "metadata",
    "session_scope",
]

#: JSONB on PostgreSQL, plain JSON everywhere else. Every JSON-valued column uses
#: this rather than bare JSONB so the same models can be created on sqlite in tests.
JSON_TYPE = JSONB(astext_type=Text()).with_variant(JSON(), "sqlite")

#: Explicit naming convention so hand-written migrations and autogenerated diffs
#: agree on constraint names.
NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Declarative base for every table in the platform.

    ``type_annotation_map`` lets a model annotate a column as
    ``Mapped[dict[str, Any]]`` or ``Mapped[list[str]]`` and get :data:`JSON_TYPE`, and
    ``Mapped[datetime]`` and get a timezone-aware timestamp, without repeating the
    type on every column.

    Note: SQLAlchemy resolves annotations by exact match, and a doubly-nested generic
    such as ``list[dict[str, Any]]`` does not resolve reliably under
    ``from __future__ import annotations``. Columns of that shape pass
    :data:`JSON_TYPE` to ``mapped_column`` explicitly.
    """

    metadata = MetaData(naming_convention=NAMING_CONVENTION)

    type_annotation_map = {  # noqa: RUF012 - SQLAlchemy reads this as a class attr
        dict[str, Any]: JSON_TYPE,
        list[str]: JSON_TYPE,
        dict[str, float]: JSON_TYPE,
        datetime: DateTime(timezone=True),
    }


#: Shared metadata, used by Alembic's ``target_metadata`` and by test fixtures.
metadata = Base.metadata


def _connect_args(settings: Settings) -> dict[str, Any]:
    """Build driver connect args for the configured backend.

    Args:
        settings: Active settings.

    Returns:
        Keyword arguments for ``create_async_engine(connect_args=...)``. asyncpg
        takes ``ssl`` rather than libpq's ``sslmode``, and a server-side
        ``statement_timeout`` is applied per connection.
    """
    url = settings.database_url
    if not url.startswith("postgresql+asyncpg"):
        # sqlite+aiosqlite in tests: no TLS, no server settings.
        return {}
    args: dict[str, Any] = {
        "server_settings": {
            "statement_timeout": str(settings.postgres_statement_timeout_ms),
            "application_name": settings.service_name,
        }
    }
    if settings.postgres_sslmode in {"require", "verify-full"}:
        args["ssl"] = True
    elif settings.postgres_sslmode == "disable":
        args["ssl"] = False
    return args


#: Engines and session factories are cached by database URL. Settings instances are
#: pydantic models and therefore unhashable, so they cannot be part of a cache key.
_ENGINES: dict[str, AsyncEngine] = {}
_SESSIONMAKERS: dict[str, async_sessionmaker[AsyncSession]] = {}


def _engine_for(url: str, settings: Settings) -> AsyncEngine:
    """Create (and cache) an engine for one database URL.

    Args:
        url: SQLAlchemy async URL; the cache key.
        settings: Active settings supplying pool sizing and TLS mode.

    Returns:
        A configured :class:`AsyncEngine`, shared across callers for this URL.
    """
    cached = _ENGINES.get(url)
    if cached is not None:
        return cached

    is_sqlite = url.startswith("sqlite")
    kwargs: dict[str, Any] = {
        "echo": settings.postgres_echo,
        "future": True,
        "pool_pre_ping": True,
        "connect_args": _connect_args(settings),
    }
    if is_sqlite:
        # In-memory/file sqlite in tests: pooling adds nothing and breaks isolation.
        kwargs["poolclass"] = NullPool
    else:
        kwargs.update(
            pool_size=settings.postgres_pool_size,
            max_overflow=settings.postgres_max_overflow,
            pool_timeout=settings.postgres_pool_timeout_seconds,
            pool_recycle=settings.postgres_pool_recycle_seconds,
        )
    engine = create_async_engine(url, **kwargs)

    if is_sqlite:

        @event.listens_for(engine.sync_engine, "connect")
        def _enable_fk(dbapi_connection: Any, _record: Any) -> None:
            """Turn on foreign-key enforcement, which sqlite disables by default."""
            cursor = dbapi_connection.cursor()
            cursor.execute("PRAGMA foreign_keys=ON")
            cursor.close()

    _ENGINES[url] = engine
    return engine


def get_engine(settings: Settings | None = None) -> AsyncEngine:
    """Return the process-wide engine for the configured database.

    Args:
        settings: Settings to build the engine from. Defaults to
            :func:`ragcore.settings.get_settings`.

    Returns:
        A cached :class:`AsyncEngine`.
    """
    cfg = settings or get_settings()
    return _engine_for(cfg.database_url, cfg)


def _sessionmaker_for(url: str, settings: Settings) -> async_sessionmaker[AsyncSession]:
    """Create (and cache) a session factory for one database URL.

    Args:
        url: SQLAlchemy async URL; the cache key.
        settings: Active settings.

    Returns:
        A configured :class:`async_sessionmaker`, shared across callers for this URL.
    """
    cached = _SESSIONMAKERS.get(url)
    if cached is not None:
        return cached
    factory = async_sessionmaker(
        bind=_engine_for(url, settings),
        expire_on_commit=False,
        autoflush=False,
        class_=AsyncSession,
    )
    _SESSIONMAKERS[url] = factory
    return factory


def get_sessionmaker(
    settings: Settings | None = None,
) -> async_sessionmaker[AsyncSession]:
    """Return the process-wide async session factory.

    Args:
        settings: Settings to build the factory from. Defaults to
            :func:`ragcore.settings.get_settings`.

    Returns:
        A cached :class:`async_sessionmaker`.
    """
    cfg = settings or get_settings()
    return _sessionmaker_for(cfg.database_url, cfg)


async def get_session() -> AsyncIterator[AsyncSession]:
    """Yield a database session, for use as a FastAPI dependency.

    The session is rolled back and closed on the way out, so an unhandled exception
    in a route can never leave a half-applied write behind.

    Yields:
        An :class:`AsyncSession` with no transaction begun.

    Example:
        >>> from fastapi import Depends
        >>> async def route(session: AsyncSession = Depends(get_session)) -> None: ...
    """
    factory = get_sessionmaker()
    session = factory()
    try:
        yield session
    except Exception:
        await session.rollback()
        raise
    finally:
        await session.close()


@asynccontextmanager
async def session_scope(
    settings: Settings | None = None,
) -> AsyncIterator[AsyncSession]:
    """Yield a database session for non-HTTP callers.

    Args:
        settings: Settings to resolve the engine from. Defaults to
            :func:`ragcore.settings.get_settings`.

    Yields:
        An :class:`AsyncSession` with no transaction begun. Rolled back and closed
        on exit.
    """
    factory = get_sessionmaker(settings)
    session = factory()
    try:
        yield session
    except Exception:
        await session.rollback()
        raise
    finally:
        await session.close()


async def dispose_engine(settings: Settings | None = None) -> None:
    """Close the connection pool.

    Call from an application shutdown hook so Azure does not see abandoned
    connections after a scale-in event.

    Args:
        settings: Settings identifying which engine to dispose. Defaults to
            :func:`ragcore.settings.get_settings`.
    """
    cfg = settings or get_settings()
    url = cfg.database_url
    engine = _ENGINES.pop(url, None)
    _SESSIONMAKERS.pop(url, None)
    if engine is not None:
        await engine.dispose()


async def check_database(settings: Settings | None = None) -> bool:
    """Probe database connectivity for ``/readyz``.

    Args:
        settings: Settings identifying the database. Defaults to
            :func:`ragcore.settings.get_settings`.

    Returns:
        True when a trivial query succeeds.

    Raises:
        Exception: Propagates the driver error so the readiness probe can report
            why the database is unreachable.
    """
    async with session_scope(settings) as session:
        await session.execute(text("SELECT 1"))
    return True
