"""Session and durable memory for the RAG pipeline (requirements #2, #3, #5).

Four independent surfaces, all of which the orchestrator composes but none of which
depend on each other at import time:

* :mod:`app.rag.memory.short_term` -- the session window (pipeline stage 2 and 9):
  Redis-backed with an in-memory fallback, rolling-summary maintenance, pinning and
  turn-level token accounting measured with Claude's own tokenizer.
* :mod:`app.rag.memory.long_term` -- durable per-user memories in ``rag_memories``
  (stages 2 and 13): salience-weighted dense recall with decay, structured write-back,
  supersede-based updating, TTL expiry and a hard consent gate.
* :mod:`app.rag.memory.semantic_cache` -- the similar-query retrieval cache
  (stage 4): caches the retrieval *plan*, never the rendered answer, and always
  re-fetches cached chunk ids through the live ACL filter.
* :mod:`app.rag.memory.consolidate` -- the periodic job that merges near-duplicate
  memories, decays salience, expires stale entries and refreshes the user profile.

Submodules are re-exported lazily through :func:`__getattr__` so that importing
``app.rag.memory`` costs nothing: ``long_term`` and ``semantic_cache`` pull
``qdrant-client``, which the short-term path does not need.
"""

from __future__ import annotations

import importlib
from typing import TYPE_CHECKING, Any

from ragcore.models.memory import LongTermMemory, UserProfile

if TYPE_CHECKING:  # pragma: no cover - import-time typing only
    from collections.abc import Sequence

    from ragcore.settings import Settings

__all__ = [
    "EXTRA_SETTING_DEFAULTS",
    "CacheProbe",
    "ChunkResolver",
    "CompactionOutcome",
    "ConsolidationReport",
    "ExtractedMemory",
    "InMemorySessionStore",
    "LongTermMemoryStore",
    "MemoryConsolidator",
    "MemoryExtraction",
    "MemoryRecall",
    "RedisSessionStore",
    "SemanticCache",
    "SessionStore",
    "SessionWindow",
    "ShortTermMemory",
    "TokenCounter",
    "get_long_term_memory",
    "get_semantic_cache",
    "get_short_term_memory",
    "optional_setting",
    "render_memory_block",
    "render_preferences",
    "reset_long_term_memory",
    "reset_semantic_cache",
    "reset_short_term_memory",
    "retrieve_by_ids",
    "summarise_turns",
]


#: Tunables this package needs that ``ragcore.settings`` does not yet declare.
#:
#: Every one of them is read through :func:`optional_setting`, so the moment the
#: corresponding ``RAG_``-prefixed field is added to :class:`ragcore.settings.Settings`
#: the field wins and this table stops being consulted. Nothing in this package reads
#: a threshold, limit, model name or key prefix from anywhere else. See the
#: "Addendum M" section of ``docs/CONTRACTS.md``.
EXTRA_SETTING_DEFAULTS: dict[str, Any] = {
    # Periodic (not merely reactive) context suppression -- requirement #5.
    "context_compact_every_n_turns": 6,
    # Parallelism for per-item ``count_tokens`` measurement.
    "context_token_count_concurrency": 8,
    # Bound on the token-count memo, in entries.
    "context_token_cache_entries": 4096,
    # Exact-measurement shed passes allowed before the assembler strips the prompt
    # down to the mandatory system + question payload.
    "context_fit_max_passes": 3,
    # Retrieved chunks kept even under extreme pressure, when any were retrieved.
    "context_min_retrieved_chunks": 1,
    # Marginal-value multiplier applied to a near-duplicate retrieved chunk. A
    # near-duplicate carries almost no new information, so it is shed first.
    "context_duplicate_penalty": 0.35,
    # Place a second cache breakpoint at the end of the stable history prefix.
    "context_cache_history_breakpoint": True,
    # Minimum measured history tokens before that breakpoint is worth writing. The
    # Anthropic minimum cacheable prefix on claude-opus-5 is 512 tokens.
    "context_cache_history_min_tokens": 1024,
    # Redis key prefix for the session window.
    "redis_session_prefix": "rag:session:",
    # Semantic-cache entries kept per (tenant, filter_fingerprint) bucket before
    # LRU-ish eviction by hit_count then last_used_at.
    "memory_cache_max_entries": 500,
    # Rows scanned per consolidation pass, per user.
    "memory_consolidate_batch_size": 200,
    # Candidate oversampling factor for salience-weighted memory recall.
    "memory_recall_oversample": 4,
    # Weight given to dense similarity versus decayed salience when ranking recall
    # candidates. 1.0 is pure similarity, 0.0 is pure salience.
    "memory_recall_similarity_weight": 0.7,
    # Memories required before the rolling profile is regenerated by MODEL_FAST.
    "memory_profile_min_memories": 3,
}

#: Where each lazily re-exported symbol lives.
_LAZY_EXPORTS: dict[str, str] = {
    "CacheProbe": "app.rag.memory.semantic_cache",
    "ChunkResolver": "app.rag.memory.semantic_cache",
    "CompactionOutcome": "app.rag.memory.short_term",
    "ConsolidationReport": "app.rag.memory.consolidate",
    "ExtractedMemory": "app.rag.memory.long_term",
    "InMemorySessionStore": "app.rag.memory.short_term",
    "LongTermMemoryStore": "app.rag.memory.long_term",
    "MemoryConsolidator": "app.rag.memory.consolidate",
    "MemoryExtraction": "app.rag.memory.long_term",
    "MemoryRecall": "app.rag.memory.long_term",
    "RedisSessionStore": "app.rag.memory.short_term",
    "SemanticCache": "app.rag.memory.semantic_cache",
    "SessionStore": "app.rag.memory.short_term",
    "SessionWindow": "app.rag.memory.short_term",
    "ShortTermMemory": "app.rag.memory.short_term",
    "TokenCounter": "app.rag.memory.short_term",
    "get_long_term_memory": "app.rag.memory.long_term",
    "get_semantic_cache": "app.rag.memory.semantic_cache",
    "get_short_term_memory": "app.rag.memory.short_term",
    "reset_long_term_memory": "app.rag.memory.long_term",
    "reset_semantic_cache": "app.rag.memory.semantic_cache",
    "reset_short_term_memory": "app.rag.memory.short_term",
    "retrieve_by_ids": "app.rag.memory.semantic_cache",
    "summarise_turns": "app.rag.memory.short_term",
}


def optional_setting(settings: Settings, name: str) -> Any:
    """Read a tunable, preferring the real settings field over the local default.

    The rule "every tunable is a settings field with a default, never a literal at a
    call site" still holds: this indirection exists only so a knob this package needs
    can be introduced without editing :mod:`ragcore.settings`, and it disappears the
    moment the field is declared there.

    Args:
        settings: Active settings object.
        name: Field name, e.g. ``"context_compact_every_n_turns"``.

    Returns:
        ``getattr(settings, name)`` when the field exists, otherwise the entry from
        :data:`EXTRA_SETTING_DEFAULTS`.

    Raises:
        KeyError: If ``name`` is neither a settings field nor a declared default,
            which is a programming error rather than a configuration one.
    """
    value = getattr(settings, name, None)
    if value is not None:
        return value
    return EXTRA_SETTING_DEFAULTS[name]


def render_memory_block(
    memories: Sequence[LongTermMemory], *, max_items: int | None = None
) -> str:
    """Render long-term memories for the answer prompt's user turn.

    Memory text is model-authored and PII-redacted before storage, so it is safe to
    place in a prompt. It goes in the *user* turn rather than the system prompt
    because it varies per user and would otherwise destroy the cached prefix.

    Args:
        memories: Memories to render, most relevant first.
        max_items: Optional cap on how many lines are rendered.

    Returns:
        One ``- (kind) text`` line per memory, or an empty string when there is
        nothing to inject.
    """
    selected = list(memories)[:max_items] if max_items else list(memories)
    if not selected:
        return ""
    return "\n".join(f"- ({memory.kind.value}) {memory.text}" for memory in selected)


def render_preferences(profile: UserProfile | None) -> str:
    """Render the rolling user profile as a preferences block.

    Args:
        profile: The user's profile, or None when memory is off or unknown.

    Returns:
        A short block for the user turn, or an empty string when the profile carries
        nothing worth spending tokens on.
    """
    if profile is None or not profile.has_content:
        return ""
    lines: list[str] = []
    if profile.preferred_style:
        lines.append(f"- preferred answer style: {profile.preferred_style}")
    if profile.preferred_language:
        lines.append(f"- preferred language: {profile.preferred_language}")
    if profile.top_topics:
        lines.append(f"- recurring topics: {', '.join(profile.top_topics)}")
    if profile.summary:
        lines.append(f"- profile: {profile.summary}")
    return "\n".join(lines)


def __getattr__(name: str) -> Any:
    """Resolve a lazily re-exported submodule symbol.

    Args:
        name: Attribute being imported from this package.

    Returns:
        The resolved object.

    Raises:
        AttributeError: If the name is not part of the public surface.
    """
    module_path = _LAZY_EXPORTS.get(name)
    if module_path is None:
        msg = f"module {__name__!r} has no attribute {name!r}"
        raise AttributeError(msg)
    value = getattr(importlib.import_module(module_path), name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    """List the public surface, including the lazily loaded names.

    Returns:
        Sorted attribute names.
    """
    return sorted(set(__all__) | set(globals()))
